### PR TITLE
Remove composer.lock from project

### PR DESCRIPTION
**Pull request by radmen**
Seems that this was added by mistake. This PR will solve this :)

### CODE REVIEW

**Comment by rdohms** [comment]
IMO, leave the `composer.lock` file in and use this http://blog.wyrihaximus.net/2015/06/test-lowest-current-and-highest-possible-on-travis/

**Comment by radmen** [comment]
@rdohms do I understand correctly - you suggest keeping `composer.lock` and configuring Travis env according to the article?

**Comment by rdohms** [comment]
@radmen yes, this way you can still test scenarios with new versions of dependencies, and avoid the scenario where a PR breaks not because of the new code submitted in it, but a random dependency break. Means contributors have to deal with less chaos monkeys.

**Comment by radmen** [comment]
@rdohms there's something I don't understand in this approach. If there's a dependency break it will occur after package is installed in a project. AFAIR Composer is not using `composer.lock` from packages so this is something which needs to be solved by the contributors. 

Another thing - if Travis is set to use _highest_ and _lowest_ deps `composer.lock` will be completely ignored since Travis will run `composer update`.

What am I missing?

**Comment by radmen** [comment]
I've reread the article and I see that I missed that _highest_ / _lowest_ envs are simply an addition.
I think that I understand the point about commiting `composer.lock` to the project. 

All the time I was used to the idea that we shouldn't commit `composer.lock` simply to avoid the mess it can generate in repository (conflicts).

Thanks @rdohms for some new knowledge. I think this PR can be closed :)

**Comment by rdohms** [comment]
@radmen `composer.lock` only plays a role when this library is the root package, i.e. when you are contributing to the package.
If the lock file is in there then a contributor can write his PR and have the same vendors as the owner of the repo, so he knows what he is coding against.
Without the lock file, when he runs `composer install` he will **possibly** get a different set, which will also happen in travis when it runs any test, so he may get breakages due to these changes, even not having "caused" them.

With the scenario in the article, you are clearly signalling which builds run with "lower/latest". A contributor can easily see that his tests against the "known set" are ok, but something else is breaking in these other scenarios.

It just helps the contributor get a known set to code against, while still allowing the chaos monkey to run in other scenarios, but communicating these more clearly so the source of failed tests is clearer.

And yes, those lower/higher scenarios run an update so they discard the lock file.

**Comment by rdohms** [comment]
@radmen its a polemic little topic, but i have made my peace with this scenario. Glad to share it.

**Pull request closed without merging**
