### PR TITLE
Ramsey UUID 4.x support

### PR DESCRIPTION
**Pull request by ramsey**

### CODE REVIEW

**Comment by ramsey** [comment]
Version 4.0.0 is out, and all tests are passing for highest and lowest versions of dependencies for pascaldevink/shortuuid, so this PR is ready to go. Thanks!

**Comment by Majkl578** [comment]
@pascaldevink Can you please take a look? Thank you. :)

**Comment by jonnott** [comment]
+1 for this!

@ramsey as ramsey/uuid 4.0 is out, can this all be resolved now?

@pascaldevink

**Comment by pascaldevink** [comment]
The corona crisis has hit me/the company I work for hard as well, so I'm a bit busy at the moment. I should have some time tomorrow (25 of March) and hopefully I can merge this and publish a new major release.

**Comment by jonnott** [comment]
Thanks @pascaldevink - and big kudos to anyone still working on open source at this crazy time in history.

**Pull request merged**
