### PR TITLE
Remove composer.lock file

### PR DESCRIPTION
**Pull request by vinkla**
Since this is a package we can skip this file.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
:+1:

**Comment by ruudk** [comment]
See https://github.com/pascaldevink/shortuuid/pull/1

**Comment by vinkla** [comment]
@pascaldevink could you provide an explanation why you closed it?

**Comment by vinkla** [comment]
The composer.lock file just takes up space. It doesn't really help us.

**Comment by vinkla** [comment]
Composer recommends to keep the lock file in applications but in packages it is optional since Composer wont care about the file being there.

**Pull request closed without merging**
