### PR TITLE
Added attributes file

### PR DESCRIPTION
**Pull request by vinkla**
Also renamed phpunit.xml to phpunit.xml.dist

### CODE REVIEW

**Comment by sstok** [comment]
Should `composer.lock` also be added?

**Comment by vinkla** [comment]
I guess it depends on #6

**Comment by vinkla** [comment]
@pascaldevink any update on this?

**Comment by vinkla** [comment]
@pascaldevink any update on this?

**Comment by vinkla** [comment]
@pascaldevink any chance we can get this merged?

**Comment by vinkla** [comment]
@pascaldevink any chance we can get this merged?

**Comment by pascaldevink** [comment]
Please tell me why you need this? Also, please tell me more of the intent of the changes.
Even if I can lookup how git attributes work (or already know how they work), I would still like to have it somewhere in the history of this repository why it has been done.

**Comment by vinkla** [comment]
This change will make it possible to exclude the files in production with the `--prefer-dist` flag. Making the library a lot smaller.

**Comment by pascaldevink** [comment]
Thanks for that!

**Comment by vinkla** [comment]
👍

**Pull request merged**
