### PR TITLE
Allow brick/math 0.10 and 0.11

### PR DESCRIPTION
**Pull request by gharlan**
https://github.com/brick/math/releases

### CODE REVIEW

**Comment by gharlan** [comment]
Corresponding commit in ramsey/uuid: https://github.com/ramsey/uuid/commit/928a62c7152da3e8f9e35c211407d783f328b757

**Comment by jonnott** [comment]
Yes please! @pascaldevink

**Comment by jonnott** [comment]
This is a particular problem if using this package in a Laravel 9.x project, as since this commit, Laravel (9.48 and upwards) now depends on brick/math 0.10 .. https://github.com/laravel/framework/commit/1fea0692d408bc8ac886c4e6d7cd0727a258a87e

**Comment by dakur** [comment]
This blocks also upgrade to newer `brick/money` as ^0.6.0 depends on `brick/math@^0.10.0`.

**Comment by dakur** [comment]
@pascaldevink Please, could you at least answer?

**Comment by pascaldevink** [comment]
Thanks @gharlan for this bump!

**Comment by pascaldevink** [comment]
@gharlan @jonnott @dakur I just released version 4.0.0, which features the upgrades to `brick/math`, drops support for PHP 7.3, and allows PHP 8.1 and 8.2. Hope that unblock you all 🙂

**Pull request merged**
